intent:
  fields:
    mower_device:
      required: true
      selector:
        device:
          integration: stihl_imow
    action:
      required: true
      example: "toDocking"
      default: "edgeMowing"
      selector:
        select:
          options:
            - "edgeMowing"
            - "toDocking"
            - "startMowingFromPoint"
            - "startMowing"
    duration:
      selector:
        select:
          options:
            - "30"
            - "60"
            - "90"
    startpoint:
      selector:
        number:
          min: 1
          max: 4
    starttime:
      selector:
        datetime:
    endtime:
      selector:
        datetime:
