intent:
  name: Intiate an iMow Action to a Mower
  description: Intiate an iMow Action to a Mower
  fields:
    mower_device:
      name: Mower
      description: The mower to call for action
      required: true
      selector:
        device:
          integration: stihl_imow
    action:
      name: iMow Action
      description: The action the targeted mower should do
      required: true
      example: "toDocking"
      # The default field value
      default: "edgeMowing"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "edgeMowing"
            - "toDocking"
            - "startMowingFromPoint"
            - "startMowing"
    duration:
      name: (startMowingFromPoint) Mowing Duration in Minutes
      description: Mowing Duration in Minutes (only necessary if action is 'startMowingFromPoint')
      selector:
        select:
          options:
            - "30"
            - "60"
            - "90"
    startpoint:
      name: (startMowingFromPoint) Starting point
      description: Mower defined Starting point (only necessary if action is 'startMowingFromPoint' and if the mower should not start from the Dock)
      selector:
        number:
          min: 1
          max: 4

    starttime:
      name: (startMowing) Time to Start
      description: Time when the mower should start the mowing action (only necessary if action is 'startMowing')
      selector:
        datetime:

    endtime:
      name: (startMowing) Time to End
      description: Time when the mower should end the mowing action (only necessary if action is 'startMowing')
      selector:
        datetime:
