# These sponsor buttons are shown on the repository by GitHub.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

buy_me_a_coffee: chrishapunkt

# Uncomment once you have completed GitHub Sponsors enrollment
# (Settings -> Sponsors) and your profile is approved:
github: [ChrisHaPunkt]
